name: TypeScript and ESLint Check

on:
  push:
    paths:
      - 'ui/**'

jobs:
  typescript-eslint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ui/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        working-directory: ui
        run: npm install

      - name: Run TypeScript
        working-directory: ui
        run: npm run tsc
          
      - name: Run ESLint
        working-directory: ui
        run: npm run lint
          
